import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_10_METADATA, CH10_SIX_NODES } from '../../shared.ts';

export const lessonCh10_2_1: LessonConfig = {
  id: 'lesson-ch10-2-1',
  unitId: 'ch10-unit-2',
  title: 'Find the First Real Problem',
  description: 'In circuits with multiple simultaneous faults or non-ideal effects, identify which problem to address first to make progress toward correct operation.',
  stageLabel: CHAPTER_10_METADATA.stageLabel,
  prerequisites: ['lesson-ch10-1-3'],
  conceptsIntroduced: [
    'fault prioritization in multi-factor failures',
    'upstream vs downstream faults',
    'triage order: topology first, then values',
  ],
  initialNodes: CH10_SIX_NODES,
  initialCircuit: [
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n6',
      properties: { voltage: 9, internalResistance: 2 },
      name: 'Battery (9V, 2Ω internal)',
      position: { x: 120, y: 230 },
      rotation: 0,
    },
    {
      id: 'wire-top',
      type: 'wire',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 220, y: 120 },
      rotation: 0,
    },
    {
      id: 'res-series',
      type: 'resistor',
      nodeA: 'n2',
      nodeB: 'n3',
      properties: { resistance: 100 },
      name: 'Series Resistor (100Ω)',
      position: { x: 420, y: 120 },
      rotation: 0,
    },
    {
      id: 'bulb-1',
      type: 'bulb',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { resistance: 100 },
      name: 'Bulb',
      position: { x: 520, y: 230 },
      rotation: 0,
    },
    {
      id: 'wire-bottom',
      type: 'wire',
      nodeA: 'n4',
      nodeB: 'n5',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 420, y: 340 },
      rotation: 0,
    },
    {
      id: 'wire-return',
      type: 'wire',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 220, y: 340 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'When a circuit has multiple problems — a broken path AND a wrong component value, for example — you cannot fix both at once meaningfully. You must triage. The first rule of triage: an open path (broken topology) always takes priority. A circuit with an open anywhere produces zero current everywhere, making any value-level measurements meaningless. Fix topology first.',
    },
    {
      id: 'step-2',
      text: 'The second rule: upstream faults mask downstream faults. A fault near the source (broken wire from the battery, failed switch before the load) cuts power to everything downstream. Even if the downstream components were working correctly, you cannot see their behavior. Always trace from source to load and fix the first fault encountered.',
      highlights: ['bat-1', 'wire-top', 'res-series'],
    },
    {
      id: 'step-3',
      text: 'After topology is verified, move to value-level faults: incorrect resistance, wrong voltage source, unexpected internal resistance affecting terminal voltage. This layered triage — topology first, then values — means each fix reveals the next problem in a predictable order.',
      theoryCheck: {
        question: 'A circuit has an open switch AND a bulb with far too high resistance. The bulb shows no light. Which fault do you address first?',
        choices: [
          {
            id: 'tc-a',
            label: 'Replace the bulb — its resistance is clearly wrong',
            isCorrect: false,
            explanation: 'Even if you replace the bulb, the open switch means no current can flow through the circuit. The topology fault (open switch) masks all behavior and must be addressed first.',
          },
          {
            id: 'tc-b',
            label: 'Close the switch — the open path prevents all current flow and must be fixed first',
            isCorrect: true,
            explanation: 'Correct. An open switch is a topology fault. No current flows through any part of the circuit while the switch is open, so the bulb\'s resistance cannot be evaluated. Fix the open path first.',
          },
          {
            id: 'tc-c',
            label: 'Measure voltage at the bulb — the measurement will reveal the real fault',
            isCorrect: false,
            explanation: 'With an open switch, the voltage at the bulb is zero (or the source voltage with no current), which is not useful information about the bulb\'s resistance. Restore the current path before measuring.',
          },
        ],
        explanation: 'Topology faults (open paths) are always addressed before value-level faults because they mask all downstream behavior.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'A circuit is reported to not work. Inspection reveals: (1) one wire is disconnected from the battery terminal, and (2) the series resistor has the wrong value for the desired current. Which is the first fault to fix?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-a' },
      hints: ['Think about which fault prevents any current from flowing at all.'],
      choices: [
        {
          id: 'ch1-a',
          label: 'Fix the disconnected wire — the broken path stops all current and makes the resistor value irrelevant',
          isCorrect: true,
          explanation: 'Correct. A disconnected wire is a topology fault. Without a complete path, no current flows regardless of the resistor value. Fix the path first, then verify whether the resistor value needs correction.',
        },
        {
          id: 'ch1-b',
          label: 'Replace the resistor first — the wrong value causes the current error',
          isCorrect: false,
          explanation: 'The wrong resistor value is a value-level fault. But with the wire disconnected, zero current flows no matter what the resistor value is. The topology fault takes priority.',
        },
        {
          id: 'ch1-c',
          label: 'Address both simultaneously — either fix could restore operation',
          isCorrect: false,
          explanation: 'Fixing both at once is not methodical troubleshooting. Fix the topology fault first to restore current flow, then measure whether the current is correct with the existing resistor, and replace only if needed.',
        },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'A working circuit suddenly dims. Investigation shows the battery\'s internal resistance has increased significantly. Is this a topology fault or a value-level fault?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['A topology fault creates an open or short. A value-level fault changes a parameter without breaking the path.'],
      choices: [
        {
          id: 'ch2-a',
          label: 'Topology fault — increased internal resistance breaks the circuit path',
          isCorrect: false,
          explanation: 'Increased internal resistance does not break the path — current still flows. It is a non-ideal parameter change that reduces terminal voltage and therefore current. The topology (closed path) is intact.',
        },
        {
          id: 'ch2-b',
          label: 'Value-level fault — the path is still closed but a non-ideal parameter has changed, reducing available power',
          isCorrect: true,
          explanation: 'Correct. Increased internal resistance is a non-ideal DC value-level fault. The circuit path remains complete; the fault changes the effective voltage available to the load, explaining the dim output.',
        },
        {
          id: 'ch2-c',
          label: 'Not a fault — internal resistance always increases in working batteries',
          isCorrect: false,
          explanation: 'While batteries do age and internal resistance naturally increases, significantly increased internal resistance causing dim output is a fault condition worth diagnosing and addressing.',
        },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Triage Order: Topology Before Values',
      content: 'When troubleshooting a multi-fault circuit, always address topology faults first. A single open circuit anywhere in the path stops all current and makes every downstream measurement meaningless. Only after verifying a complete current path should you investigate value-level faults such as wrong resistance, excessive internal resistance, or a component exceeding its operating limit.',
    },
    {
      title: 'Upstream Faults Mask Downstream Faults',
      content: 'An upstream fault (near the source) hides the effect of all downstream faults because it prevents energy from reaching them. Trace from source to load in order, and fix the first fault encountered. Once you restore power to a section, new symptoms may appear from previously hidden faults further downstream.',
    },
  ],
  sandboxUnlocks: ['troubleshooting-prompt-set'],
  availableActions: ['inspect', 'toggle-switch'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch10-triage-order',
      title: 'Chapter 10: Triage order for multi-fault circuits',
      content: 'Step 1: verify topology (no open paths). Step 2: verify values (correct parameters). Topology faults always take priority because they mask all downstream behavior.',
      sourceLesson: 'lesson-ch10-2-1',
    },
    {
      id: 'theory-ch10-upstream-masking',
      title: 'Chapter 10: Upstream faults mask downstream faults',
      content: 'A fault near the source prevents energy from reaching downstream components, hiding any faults those components may also have. Trace from source to load, fixing the first fault found before evaluating anything further downstream.',
      sourceLesson: 'lesson-ch10-2-1',
    },
  ],
  quizzesUnlocked: ['quiz-ch10-mixed-troubleshooting-basics'],
};
