import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_8_METADATA, CH8_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh8_2_3: LessonConfig = {
  id: 'lesson-ch8-2-3',
  unitId: 'ch8-unit-2',
  title: 'Compare Unrectified and Rectified Output',
  description: 'Put an unrectified AC load and a rectified load side by side to see exactly what each one receives and why it matters.',
  stageLabel: CHAPTER_8_METADATA.stageLabel,
  prerequisites: ['lesson-ch8-2-2'],
  conceptsIntroduced: [
    'unrectified versus rectified behavior',
    'conversion stages change the kind of output the load sees',
  ],
  initialNodes: CH8_COMPARISON_NODES,
  initialCircuit: [
    // Left side: unrectified AC (nodes n1–n4)
    {
      id: 'ac-1',
      type: 'ac-source',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'Load (AC)',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: rectified AC (nodes n5–n8)
    {
      id: 'ac-2',
      type: 'ac-source',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'diode-1',
      type: 'diode',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { isForwardBiased: true },
      name: 'Diode',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { resistance: 100 },
      name: 'Load (Rectified)',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-3',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'These two circuits use the same AC source and the same load resistance. The only difference is the diode added on the right. Open the timeline panel and observe what each load receives. The left load sees full AC — current alternates in both directions on every cycle.',
      highlights: ['res-1'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-2',
      text: 'Now focus on the right load. It sees pulsed forward-only current. During the forward half of each cycle, the diode conducts and the load receives current. During the reverse half, the diode blocks and the load receives nothing. The load never experiences reverse current.',
      highlights: ['diode-1', 'res-2'],
    },
    {
      id: 'step-3',
      text: 'Consider which output is better suited for a device that needs DC-like power. The unrectified AC output changes direction constantly — many devices cannot handle that. The rectified output only flows one way, which is a necessary condition for any device that requires DC. The diode stage is what makes this possible.',
      highlights: ['res-1', 'res-2'],
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'Which output better approximates a DC power requirement: the unrectified AC or the rectified pulsed output?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-b' },
      hints: ['DC requires current to flow in only one direction. Think about which output meets that condition.'],
      choices: [
        {
          id: 'ch1-a',
          label: 'The unrectified AC — it delivers more average power to the load',
          isCorrect: false,
          explanation: 'Delivering current in both directions does not help a device that needs DC. The direction requirement matters more than average power here.',
        },
        {
          id: 'ch1-b',
          label: 'The rectified output — it only flows in one direction, which is a necessary condition for DC-like behavior',
          isCorrect: true,
          explanation: 'Correct. The rectified output satisfies the most fundamental requirement of DC: current only flows one way. That makes it a starting point for DC-dependent devices.',
        },
        {
          id: 'ch1-c',
          label: 'Neither — only a battery can power a DC device',
          isCorrect: false,
          explanation: 'Rectified pulsed current is used in real power supply designs. A battery is not the only way to provide one-directional current.',
        },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'What is the main role of the diode stage in the rectified system?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Focus on what the diode does differently compared to having no diode in the circuit.'],
      choices: [
        {
          id: 'ch2-a',
          label: 'To increase the voltage amplitude so the load receives more power',
          isCorrect: false,
          explanation: 'A diode does not boost voltage. Its role is to control the direction of current flow.',
        },
        {
          id: 'ch2-b',
          label: 'To block the reverse half of the AC cycle so the load only sees current flowing in one direction',
          isCorrect: true,
          explanation: 'Correct. The diode stage enforces one-directional flow by blocking every reverse half-cycle before it reaches the load.',
        },
        {
          id: 'ch2-c',
          label: 'To smooth out the pulsing and produce steady DC voltage',
          isCorrect: false,
          explanation: 'A diode alone does not smooth the output. Smoothing requires additional components such as capacitors. The diode only enforces directionality.',
        },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Unrectified vs Rectified Output',
      content: 'An unrectified AC load experiences current that alternates direction on every cycle — positive for one half, negative for the other. A rectified load receives only the forward half-cycles. The diode blocks reverse current entirely, so the load only sees current flowing one way.',
    },
    {
      title: 'Why Rectification Matters',
      content: 'Many devices require current that flows in one direction. Raw AC does not meet this requirement. A rectified output — though still pulsed — satisfies the directional condition. The diode stage is the component that enforces this constraint, making it the first and most fundamental stage of any AC-to-DC conversion system.',
    },
  ],
  sandboxUnlocks: [],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: true,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch8-rectified-comparison',
      title: 'Comparing unrectified and rectified output',
      content: 'Unrectified AC alternates direction on every cycle. Rectified output — produced by adding a diode in series — only flows in one direction, though it still pulses. The diode stage is what converts an alternating signal into a one-directional pulsed signal, which is a necessary step toward usable DC power.',
      sourceLesson: 'lesson-ch8-2-3',
    },
  ],
  quizzesUnlocked: ['quiz-ch8-rectified-versus-unrectified-basics'],
};
