import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_7_METADATA, CH7_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh7_2_3: LessonConfig = {
  id: 'lesson-ch7-2-3',
  unitId: 'ch7-unit-2',
  title: 'Time-Dependent Components Under AC: A Preview',
  description: 'Get a first glimpse of how capacitors behave differently from resistors under AC, and learn why this requires more advanced concepts.',
  stageLabel: CHAPTER_7_METADATA.stageLabel,
  prerequisites: ['lesson-ch7-2-2'],
  conceptsIntroduced: [
    'AC can interact with capacitors and inductors differently than DC switching',
    'the speed of repetition matters',
    'this is an introductory preview only',
    'frequency and period introduced by name',
  ],
  initialNodes: CH7_COMPARISON_NODES,
  initialCircuit: [
    // Left side: AC + resistor
    {
      id: 'ac-1',
      type: 'ac-source',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'Resistor',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: AC + capacitor
    {
      id: 'ac-2',
      type: 'ac-source',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'cap-1',
      type: 'capacitor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { capacitance: 0.001 },
      name: 'Capacitor',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-3',
      type: 'wire',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-4',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'You have already seen that a resistor under AC is straightforward: current follows voltage directly. The left circuit confirms this — the current waveform matches the voltage waveform exactly. Resistors respond the same way to every instant of the AC cycle.',
      highlights: ['ac-1', 'res-1'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-2',
      text: 'Now look at the right circuit — the same AC source but with a capacitor instead of a resistor. In Chapter 6 you saw capacitors charge and discharge once when a DC switch is toggled. Under AC, the capacitor is charged and discharged repeatedly, following the alternating voltage. The current behavior is different from a resistor, and understanding it fully requires more advanced tools than this introductory chapter provides.',
      highlights: ['ac-2', 'cap-1'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-3',
      text: 'The speed at which the AC source repeats is called its frequency — measured in cycles per second, or hertz (Hz). The time for one complete cycle is the period. The frequency matters because a capacitor interacts differently with slow versus fast repetition. For now, take note of these terms: frequency and period. Their full role in reactive AC circuits is a topic for a later chapter.',
      theoryCheck: {
        question: 'Why is understanding a capacitor under AC more complex than understanding a resistor under AC?',
        choices: [
          { id: 'tc-a', label: 'Because capacitors are physically larger and harder to model', isCorrect: false, explanation: 'Physical size is irrelevant. The complexity comes from how capacitors store and release energy in an AC cycle.' },
          { id: 'tc-b', label: 'Because the capacitor stores and releases energy during each AC cycle in a way that depends on frequency', isCorrect: true, explanation: 'Correct. A capacitor charges and discharges each AC cycle. How it behaves depends on the frequency, requiring concepts beyond Ohm\'s Law.' },
          { id: 'tc-c', label: 'Because capacitors do not work with AC sources at all', isCorrect: false, explanation: 'Capacitors absolutely interact with AC. They charge and discharge on each cycle — they just require more advanced analysis.' },
        ],
        explanation: 'Capacitors store and release energy on each AC cycle. How they respond depends on frequency, which requires concepts like reactance and impedance beyond this introductory chapter.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'Which component-source combination requires different reasoning than simple resistive AC?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-b' },
      hints: ['Which component stores energy and responds differently depending on how fast the AC repeats?'],
      choices: [
        { id: 'ch1-a', label: 'AC source + resistor', isCorrect: false, explanation: 'An AC source with a resistor follows simple rules: current follows voltage directly at every instant. No additional concepts are required.' },
        { id: 'ch1-b', label: 'AC source + capacitor (time-dependent behavior interacts with the repeating AC pattern)', isCorrect: true, explanation: 'Correct. A capacitor stores and releases energy, and its response depends on how fast the AC repeats (frequency). This requires more advanced analysis.' },
        { id: 'ch1-c', label: 'Both combinations require equally complex reasoning', isCorrect: false, explanation: 'The resistive case is straightforward. The capacitive case requires additional concepts like reactance.' },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'Why is the AC behavior of capacitors and inductors only a preview at this stage?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Think about what concepts would be needed to fully analyze a capacitor or inductor under AC.'],
      choices: [
        { id: 'ch2-a', label: 'Because capacitors and inductors are not used in real AC circuits', isCorrect: false, explanation: 'Capacitors and inductors are widely used in real AC circuits. They are essential to filters, power supplies, and many other systems.' },
        { id: 'ch2-b', label: 'Their full interaction with AC requires understanding concepts like impedance that are beyond this introductory chapter', isCorrect: true, explanation: 'Correct. Fully analyzing capacitors and inductors under AC requires impedance, reactance, and phase relationships — topics for a later chapter.' },
        { id: 'ch2-c', label: 'Because their behavior under AC is identical to their DC switching behavior', isCorrect: false, explanation: 'Their AC behavior is different from their one-time DC transient behavior. AC involves repeated charging and discharging at the AC frequency.' },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Time-Dependent Components Under AC',
      content: 'Capacitors and inductors interact with AC in a more complex way than resistors. A capacitor charges and discharges on each AC cycle. How it responds depends on the frequency of the AC source. Full analysis requires concepts like reactance and impedance.',
    },
    {
      title: 'Frequency and Period',
      content: 'Frequency is the number of complete AC cycles per second, measured in hertz (Hz). The period is the time for one complete cycle. These terms describe how fast an AC source repeats. The frequency matters when analyzing time-dependent components like capacitors and inductors.',
    },
  ],
  sandboxUnlocks: ['ac-reactive-preview'],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: true,
  formulasShown: [],
  theoryPageAdditions: [],
  quizzesUnlocked: ['quiz-ch7-introductory-ac-reactive-preview-basics'],
};
