import type { UnitConfig } from '../types/lesson.ts';

export const unitRegistry: UnitConfig[] = [
  {
    id: 'unit-1',
    title: 'First Contact With a Circuit',
    stageLabel: 'Beginner',
    description: 'Discover that a circuit must form a complete path and that a switch can control whether a bulb turns on.',
    lessons: ['lesson-1-1', 'lesson-1-2', 'lesson-1-3'],
  },
  {
    id: 'unit-2',
    title: 'Current, Voltage, and the Bulb as a Load',
    stageLabel: 'Beginner',
    description: 'Gain the first conceptual model of what flows, what pushes, and what the bulb does.',
    lessons: ['lesson-2-1', 'lesson-2-2', 'lesson-2-3', 'lesson-2-4'],
  },
  {
    id: 'unit-3',
    title: 'Resistance and Early Formula Familiarity',
    stageLabel: 'Beginner',
    description: 'Understand resistance and become familiar with the earliest formulas.',
    lessons: ['lesson-3-1', 'lesson-3-2', 'lesson-3-3'],
  },
  {
    id: 'unit-4',
    title: 'First Construction Freedom',
    stageLabel: 'Beginner',
    description: 'Take more responsibility for circuit assembly, including making and correcting mistakes.',
    lessons: ['lesson-4-1', 'lesson-4-2', 'lesson-4-3'],
  },
  {
    id: 'unit-5',
    title: 'Readiness for Numbers',
    stageLabel: 'Beginner to Early Intermediate',
    description: 'Prepare to transition from qualitative understanding to numerical analysis.',
    lessons: ['lesson-5-1', 'lesson-5-2'],
  },
  // Chapter 2: First Numerical DC Analysis
  {
    id: 'ch2-unit-1',
    title: 'First Numbers in a Circuit',
    stageLabel: 'Beginner to Early Intermediate',
    description: 'Understand that source and load have explicit numerical values that determine circuit behavior.',
    lessons: ['lesson-ch2-1-1', 'lesson-ch2-1-2', 'lesson-ch2-1-3'],
  },
  {
    id: 'ch2-unit-2',
    title: 'First Manual Use of Ohm\'s Law',
    stageLabel: 'Early Intermediate',
    description: 'Begin actively using V = IR to calculate current, resistance, and voltage.',
    lessons: ['lesson-ch2-2-1', 'lesson-ch2-2-2', 'lesson-ch2-2-3'],
  },
  {
    id: 'ch2-unit-3',
    title: 'Power Enters the Picture',
    stageLabel: 'Early Intermediate',
    description: 'Understand power as a quantitative description and begin calculating it in simple circuits.',
    lessons: ['lesson-ch2-3-1', 'lesson-ch2-3-2', 'lesson-ch2-3-3'],
  },
  {
    id: 'ch2-unit-4',
    title: 'Numerical Challenge Structure',
    stageLabel: 'Early Intermediate',
    description: 'Apply numerical reasoning inside challenges and see transparent evaluation results.',
    lessons: ['lesson-ch2-4-1', 'lesson-ch2-4-2', 'lesson-ch2-4-3'],
  },
  {
    id: 'ch2-unit-5',
    title: 'Source and Load Matching Begins',
    stageLabel: 'Early Intermediate',
    description: 'Start reasoning about whether a source and load fit together numerically.',
    lessons: ['lesson-ch2-5-1', 'lesson-ch2-5-2'],
  },
  // Chapter 3: Series and Parallel Foundations
  {
    id: 'ch3-unit-1',
    title: 'Two Bulbs in Series',
    stageLabel: 'Early Intermediate',
    description: 'Understand that a series circuit has one path and that identical bulbs in series behave differently from a single-bulb circuit.',
    lessons: ['lesson-ch3-1-1', 'lesson-ch3-1-2', 'lesson-ch3-1-3'],
  },
  {
    id: 'ch3-unit-2',
    title: 'Series Calculations',
    stageLabel: 'Early Intermediate',
    description: 'Calculate simple ideal series-circuit quantities using two identical loads first.',
    lessons: ['lesson-ch3-2-1', 'lesson-ch3-2-2', 'lesson-ch3-2-3', 'lesson-ch3-2-4'],
  },
  {
    id: 'ch3-unit-3',
    title: 'First Parallel Circuit',
    stageLabel: 'Early Intermediate',
    description: 'See and replicate a parallel structure before reasoning deeply about its behavior.',
    lessons: ['lesson-ch3-3-1', 'lesson-ch3-3-2', 'lesson-ch3-3-3', 'lesson-ch3-3-4'],
  },
  {
    id: 'ch3-unit-4',
    title: 'Parallel Calculations',
    stageLabel: 'Early Intermediate',
    description: 'Manually calculate simple ideal parallel-circuit quantities using two identical loads first, then selected unequal-load cases.',
    lessons: ['lesson-ch3-4-1', 'lesson-ch3-4-2', 'lesson-ch3-4-3', 'lesson-ch3-4-4'],
  },
  {
    id: 'ch3-unit-5',
    title: 'Unequal Loads and Flexible Solutions',
    stageLabel: 'Early Intermediate',
    description: 'Reason about circuits where loads are not identical and where more than one correct design can satisfy the challenge goal.',
    lessons: ['lesson-ch3-5-1', 'lesson-ch3-5-2', 'lesson-ch3-5-3'],
  },
  // Chapter 4: Measurement, Mixed Circuits, and Named Circuit Laws
  {
    id: 'ch4-unit-1',
    title: 'The First Measurement Tool',
    stageLabel: 'Early Intermediate to Intermediate',
    description: 'Introduce measurement as verification after manual analysis foundations.',
    lessons: ['lesson-ch4-1-1', 'lesson-ch4-1-2', 'lesson-ch4-1-3'],
  },
  {
    id: 'ch4-unit-2',
    title: 'More Tools for Inspection',
    stageLabel: 'Intermediate',
    description: 'Expand measurement from voltage to current and resistance workflows.',
    lessons: ['lesson-ch4-2-1', 'lesson-ch4-2-2', 'lesson-ch4-2-3'],
  },
  {
    id: 'ch4-unit-3',
    title: 'Mixed Circuits',
    stageLabel: 'Intermediate',
    description: 'Analyze mixed series-parallel structures with reduction and verification.',
    lessons: ['lesson-ch4-3-1', 'lesson-ch4-3-2', 'lesson-ch4-3-3', 'lesson-ch4-3-4'],
  },
  {
    id: 'ch4-unit-4',
    title: 'Source and Load Matching Becomes Stronger',
    stageLabel: 'Intermediate',
    description: 'Reason about target operating ranges and debug failing designs.',
    lessons: ['lesson-ch4-4-1', 'lesson-ch4-4-2'],
  },
  {
    id: 'ch4-unit-5',
    title: 'Named Laws and Chapter Review',
    stageLabel: 'Intermediate',
    description: 'Apply KCL and KVL naming in guided contexts and integrated review tasks.',
    lessons: ['lesson-ch4-5-1', 'lesson-ch4-5-2', 'lesson-ch4-5-3'],
  },
  // Chapter 5: Non-Ideal Behavior and Operating Limits
  {
    id: 'ch5-unit-1',
    title: 'Ideal Models Are Useful, But Not Complete',
    stageLabel: 'Intermediate',
    description: 'Understand why the simulation now begins introducing non-ideal behavior.',
    lessons: ['lesson-ch5-1-1', 'lesson-ch5-1-2'],
  },
  {
    id: 'ch5-unit-2',
    title: 'Internal Resistance of the Source',
    stageLabel: 'Intermediate',
    description: 'Understand that a source may not behave like a perfect ideal voltage source under load.',
    lessons: ['lesson-ch5-2-1', 'lesson-ch5-2-2', 'lesson-ch5-2-3', 'lesson-ch5-2-4'],
  },
  {
    id: 'ch5-unit-3',
    title: 'Wire Resistance',
    stageLabel: 'Intermediate',
    description: 'Understand that wires themselves can affect circuit behavior when they are not treated as ideal.',
    lessons: ['lesson-ch5-3-1', 'lesson-ch5-3-2', 'lesson-ch5-3-3'],
  },
  {
    id: 'ch5-unit-4',
    title: 'Heating and Failure',
    stageLabel: 'Intermediate',
    description: 'Understand that excessive operating conditions can create heat and can damage or destroy components in the simulation.',
    lessons: ['lesson-ch5-4-1', 'lesson-ch5-4-2', 'lesson-ch5-4-3'],
  },
  {
    id: 'ch5-unit-5',
    title: 'Tolerances and Variability',
    stageLabel: 'Intermediate',
    description: 'Understand that not all component values must be treated as perfectly exact in a more realistic simulation.',
    lessons: ['lesson-ch5-5-1', 'lesson-ch5-5-2', 'lesson-ch5-5-3'],
  },
  // Chapter 6: Capacitors, Inductors, and Time-Dependent Behavior
  {
    id: 'ch6-unit-1',
    title: 'Circuits Can Change Over Time',
    stageLabel: 'Intermediate to Late Intermediate',
    description: 'Understand that some circuits have behavior that unfolds over time rather than appearing instantly in a final state.',
    lessons: ['lesson-ch6-1-1', 'lesson-ch6-1-2'],
  },
  {
    id: 'ch6-unit-2',
    title: 'Capacitors',
    stageLabel: 'Late Intermediate',
    description: 'Explore the capacitor as a component whose behavior changes over time and can be described in terms of storing electrical energy in the simplified instructional model.',
    lessons: ['lesson-ch6-2-1', 'lesson-ch6-2-2', 'lesson-ch6-2-3', 'lesson-ch6-2-4'],
  },
  {
    id: 'ch6-unit-3',
    title: 'Inductors',
    stageLabel: 'Late Intermediate',
    description: 'Explore the inductor as another time-dependent component with behavior that differs from the capacitor.',
    lessons: ['lesson-ch6-3-1', 'lesson-ch6-3-2', 'lesson-ch6-3-3', 'lesson-ch6-3-4'],
  },
  {
    id: 'ch6-unit-4',
    title: 'Capacitors Versus Inductors',
    stageLabel: 'Late Intermediate',
    description: 'Compare capacitor and inductor behaviors directly and understand that they are not interchangeable.',
    lessons: ['lesson-ch6-4-1', 'lesson-ch6-4-2'],
  },
  {
    id: 'ch6-unit-5',
    title: 'First Time-Aware Design Challenges',
    stageLabel: 'Late Intermediate',
    description: 'Apply time-dependent reasoning in guided and semi-open-ended challenges involving both initial and steady-state behavior.',
    lessons: ['lesson-ch6-5-1', 'lesson-ch6-5-2', 'lesson-ch6-5-3'],
  },
  // Chapter 7: AC Fundamentals and DC/AC Conversion
  {
    id: 'ch7-unit-1',
    title: 'What AC Is',
    stageLabel: 'Late Intermediate',
    description: 'Understand alternating current as a distinct source and behavior model, and see how it differs from the DC circuits studied so far.',
    lessons: ['lesson-ch7-1-1', 'lesson-ch7-1-2', 'lesson-ch7-1-3'],
  },
  {
    id: 'ch7-unit-2',
    title: 'AC Loads and Comparison With DC',
    stageLabel: 'Late Intermediate',
    description: 'Compare how loads behave under AC and DC in the simplified simulation model.',
    lessons: ['lesson-ch7-2-1', 'lesson-ch7-2-2', 'lesson-ch7-2-3'],
  },
  {
    id: 'ch7-unit-3',
    title: 'Conversion Between DC and AC',
    stageLabel: 'Late Intermediate',
    description: 'Understand that some systems use conversion stages to move between DC and AC.',
    lessons: ['lesson-ch7-3-1', 'lesson-ch7-3-2', 'lesson-ch7-3-3'],
  },
  {
    id: 'ch7-unit-4',
    title: 'Modern Mixed-System Example',
    stageLabel: 'Late Intermediate',
    description: 'Analyze a practical conceptual example involving both DC and AC stages.',
    lessons: ['lesson-ch7-4-1', 'lesson-ch7-4-2'],
  },
  {
    id: 'ch7-unit-5',
    title: 'AC and Conversion Review',
    stageLabel: 'Late Intermediate',
    description: 'Integrate AC basics, AC/DC comparison, and conversion-stage reasoning in review challenges.',
    lessons: ['lesson-ch7-5-1', 'lesson-ch7-5-2'],
  },
  // Chapter 8: Diodes, Transistors, Rectification, and Switching
  {
    id: 'ch8-unit-1',
    title: 'Diodes',
    stageLabel: 'Late Intermediate',
    description: 'Understand the diode as a component with directional behavior and learn to use it in simple DC circuits.',
    lessons: ['lesson-ch8-1-1', 'lesson-ch8-1-2', 'lesson-ch8-1-3'],
  },
  {
    id: 'ch8-unit-2',
    title: 'Rectification',
    stageLabel: 'Late Intermediate - Active Components',
    description: 'See how diode directionality connects to AC/DC conversion through introductory rectification.',
    lessons: ['lesson-ch8-2-1', 'lesson-ch8-2-2', 'lesson-ch8-2-3'],
  },
  {
    id: 'ch8-unit-3',
    title: 'Transistors',
    stageLabel: 'Late Intermediate - Active Components',
    description: 'Understand the transistor as a component used for switching and controlling circuit behavior.',
    lessons: ['lesson-ch8-3-1', 'lesson-ch8-3-2', 'lesson-ch8-3-3'],
  },
  {
    id: 'ch8-unit-4',
    title: 'Switching and Control Systems',
    stageLabel: 'Late Intermediate - Active Components',
    description: 'Apply diode and transistor concepts in simple switching and control design problems.',
    lessons: ['lesson-ch8-4-1', 'lesson-ch8-4-2'],
  },
  {
    id: 'ch8-unit-5',
    title: 'Diodes, Rectification, and Switching Review',
    stageLabel: 'Late Intermediate - Active Components',
    description: 'Integrate diode behavior, rectification, transistor switching, and component-choice reasoning.',
    lessons: ['lesson-ch8-5-1', 'lesson-ch8-5-2'],
  },
  // Chapter 9: Logic Gates and Digital-Style Behavior
  {
    id: 'ch9-unit-1',
    title: 'From Switching to Logic',
    stageLabel: 'Advanced Beginner Electronics to Early Digital Logic',
    description: 'Understand how transistor-style switching can be reframed as digital-style input and output state behavior.',
    lessons: ['lesson-ch9-1-1', 'lesson-ch9-1-2'],
  },
  {
    id: 'ch9-unit-2',
    title: 'Basic Logic Gates',
    stageLabel: 'Early Digital Logic',
    description: 'Learn the behavior of NOT, AND, OR gates and how truth tables systematically describe them.',
    lessons: ['lesson-ch9-2-1', 'lesson-ch9-2-2', 'lesson-ch9-2-3', 'lesson-ch9-2-4', 'lesson-ch9-2-5'],
  },
  {
    id: 'ch9-unit-3',
    title: 'More Gate Variants',
    stageLabel: 'Early Digital Logic',
    description: 'Extend your gate vocabulary with NAND, NOR, and XOR, and understand what makes each useful.',
    lessons: ['lesson-ch9-3-1', 'lesson-ch9-3-2'],
  },
  {
    id: 'ch9-unit-4',
    title: 'Small Logic Designs',
    stageLabel: 'Early Digital Logic to Introductory System Design',
    description: 'Apply gate behavior to small design problems by choosing and combining gates to meet specific output rules.',
    lessons: ['lesson-ch9-4-1', 'lesson-ch9-4-2', 'lesson-ch9-4-3'],
  },
  {
    id: 'ch9-unit-5',
    title: 'Logic and Digital-Style Review',
    stageLabel: 'Introductory System Design',
    description: 'Integrate the chapter\'s gate and logic-design ideas in guided and open-ended review challenges.',
    lessons: ['lesson-ch9-5-1', 'lesson-ch9-5-2'],
  },
];
