import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_7_METADATA, CH7_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh7_1_1: LessonConfig = {
  id: 'lesson-ch7-1-1',
  unitId: 'ch7-unit-1',
  title: 'Direct Current Versus Alternating Current',
  description: 'Compare DC and AC sources side by side and discover how alternating current differs fundamentally from direct current.',
  stageLabel: CHAPTER_7_METADATA.stageLabel,
  prerequisites: ['chapter-6-complete'],
  conceptsIntroduced: [
    'DC as steady or one-directional source',
    'AC as alternating-direction source',
    'current direction varies over time in AC',
  ],
  initialNodes: CH7_COMPARISON_NODES,
  initialCircuit: [
    // Left side: DC circuit (nodes n1–n4)
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'DC Source (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'Resistor (DC)',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: AC circuit (nodes n5–n8)
    {
      id: 'ac-1',
      type: 'ac-source',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { resistance: 100 },
      name: 'Resistor (AC)',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-3',
      type: 'wire',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-4',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'The circuit on the left uses a DC source — a battery. DC stands for Direct Current. The voltage and current from a DC source always push in the same direction. The current through the resistor is constant and never reverses.',
      highlights: ['bat-1', 'res-1'],
    },
    {
      id: 'step-2',
      text: 'The circuit on the right uses an AC source. AC stands for Alternating Current. Unlike a battery, an AC source repeatedly reverses its polarity over time. The current through the resistor alternates direction — it goes one way, then the other, then back again, continuously.',
      highlights: ['ac-1', 'res-2'],
    },
    {
      id: 'step-3',
      text: 'Open the timeline panel and observe both circuits. The DC side shows a constant flat line. The AC side shows a pattern that keeps repeating and changing direction. Both use the same resistor value, but the source type determines how the current behaves.',
      showCurrentOverlay: true,
      theoryCheck: {
        question: 'What is the key difference between DC and AC current in a circuit?',
        choices: [
          { id: 'tc-a', label: 'DC current alternates direction over time while AC current stays constant', isCorrect: false, explanation: 'This is reversed. It is AC current that alternates, not DC.' },
          { id: 'tc-b', label: 'AC current alternates direction over time while DC current maintains one direction', isCorrect: true, explanation: 'Correct. AC alternates direction repeatedly while DC always flows in one direction.' },
          { id: 'tc-c', label: 'Both DC and AC produce alternating current but at different frequencies', isCorrect: false, explanation: 'DC does not alternate at all. Only AC alternates direction.' },
        ],
        explanation: 'AC (Alternating Current) repeatedly reverses direction over time. DC (Direct Current) always flows in one direction.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'Which source produces current that alternates direction over time?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-b' },
      hints: ['Observe the AC circuit on the right side of the workspace.'],
      choices: [
        { id: 'ch1-a', label: 'The DC source (battery)', isCorrect: false, explanation: 'A battery provides constant current in one direction. It does not alternate.' },
        { id: 'ch1-b', label: 'The AC source', isCorrect: true, explanation: 'Correct. An AC source repeatedly reverses polarity, causing the current to alternate direction continuously.' },
        { id: 'ch1-c', label: 'Both the DC and AC sources', isCorrect: false, explanation: 'Only the AC source alternates. The DC source maintains a single direction.' },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'Which best describes how AC differs from DC?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Think about what happens to current direction over time for each source type.'],
      choices: [
        { id: 'ch2-a', label: 'AC has a higher voltage than DC in all practical circuits', isCorrect: false, explanation: 'Voltage level is independent of the AC vs DC distinction. Both can be high or low voltage.' },
        { id: 'ch2-b', label: 'AC voltage and current change direction repeatedly while DC maintains one direction', isCorrect: true, explanation: 'Correct. This is the defining difference: AC alternates direction, DC does not.' },
        { id: 'ch2-c', label: 'DC is only used in high-power applications while AC is used in low-power ones', isCorrect: false, explanation: 'Both AC and DC are used across a wide range of power levels. The key distinction is direction of current flow over time.' },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Direct Current (DC)',
      content: 'DC sources, such as batteries, provide voltage and current in a single, constant direction. The current through a DC circuit does not change direction over time.',
    },
    {
      title: 'Alternating Current (AC)',
      content: 'AC sources repeatedly reverse their polarity over time. The current through an AC circuit alternates direction in a repeating pattern, unlike the one-directional flow of DC.',
    },
  ],
  sandboxUnlocks: ['ac-source'],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: true,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch7-ac-vs-dc',
      title: 'What is AC?',
      content: 'AC stands for Alternating Current. Unlike DC (Direct Current), which flows in one direction, AC repeatedly reverses direction. The rate of reversal is described by the frequency of the AC source.',
      sourceLesson: 'lesson-ch7-1-1',
    },
    {
      id: 'theory-ch7-dc-vs-ac-comparison',
      title: 'AC versus DC',
      content: 'DC sources (such as batteries) provide steady, one-directional current. AC sources reverse polarity on a repeating cycle. The same resistive load responds differently depending on source type: constant current under DC, alternating current under AC.',
      sourceLesson: 'lesson-ch7-1-1',
    },
  ],
  quizzesUnlocked: ['quiz-ch7-ac-versus-dc-basics'],
};
