import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_8_METADATA, CH8_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh8_3_2: LessonConfig = {
  id: 'lesson-ch8-3-2',
  unitId: 'ch8-unit-3',
  title: 'A Transistor as a Switch',
  description: 'Compare a transistor-on circuit to a transistor-off circuit and see how electronic switching differs from a mechanical switch.',
  stageLabel: CHAPTER_8_METADATA.stageLabel,
  prerequisites: ['lesson-ch8-3-1'],
  conceptsIntroduced: [
    'transistor switch behavior',
    'a control condition can turn another path on or off',
    'switching can be done electronically not only mechanically',
  ],
  initialNodes: CH8_COMPARISON_NODES,
  initialCircuit: [
    // Left side: transistor ON (nodes n1–n4)
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'Battery (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'transistor-1',
      type: 'transistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { controlEnabled: true },
      name: 'Transistor (ON)',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: transistor OFF (nodes n5–n8)
    {
      id: 'bat-2',
      type: 'battery',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { voltage: 9 },
      name: 'Battery (9V)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'transistor-2',
      type: 'transistor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { controlEnabled: false },
      name: 'Transistor (OFF)',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'Look at the left circuit. The transistor\'s control is enabled (ON). Current flows from the battery, through the transistor, and to the load. The load is operating. The transistor is conducting — it behaves exactly like a closed switch in this state.',
      highlights: ['transistor-1', 'res-1'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-2',
      text: 'Now look at the right circuit. The transistor\'s control is disabled (OFF). The transistor blocks the current path. No current reaches the load, and the load does not operate. The transistor behaves exactly like an open switch in this state.',
      highlights: ['transistor-2', 'res-2'],
    },
    {
      id: 'step-3',
      text: 'Compare this to a mechanical switch: both open and close a circuit path. The key difference is how they are controlled. A mechanical switch requires physical contact — a person or mechanism must physically move it. The transistor is controlled by an electronic signal — no physical contact required. This makes the transistor useful for automated, fast, and remote switching.',
      highlights: ['transistor-1', 'transistor-2'],
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'When is the transistor allowing the load to operate in these circuits?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-a' },
      hints: ['Look at which circuit has the transistor\'s control enabled.'],
      choices: [
        {
          id: 'ch1-a',
          label: 'When the transistor\'s control is enabled (left circuit — transistor ON)',
          isCorrect: true,
          explanation: 'Correct. An enabled control signal causes the transistor to conduct, allowing current to reach the load.',
        },
        {
          id: 'ch1-b',
          label: 'When the transistor\'s control is disabled (right circuit — transistor OFF)',
          isCorrect: false,
          explanation: 'A disabled control signal causes the transistor to block. The load receives no current in the right circuit.',
        },
        {
          id: 'ch1-c',
          label: 'Both circuits allow the load to operate equally',
          isCorrect: false,
          explanation: 'Only the circuit with the transistor ON allows the load to operate. The transistor OFF circuit blocks current entirely.',
        },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'What is the key advantage of a transistor switch compared to a mechanical switch for electronic control?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Think about how each type of switch is controlled and what that means for automation.'],
      choices: [
        {
          id: 'ch2-a',
          label: 'A transistor switch never wears out, unlike a mechanical switch',
          isCorrect: false,
          explanation: 'While transistors do have longevity advantages, the key instructional point here is the electronic control mechanism, not durability.',
        },
        {
          id: 'ch2-b',
          label: 'The transistor can be controlled by an electronic signal rather than physical contact, making automated or fast switching possible',
          isCorrect: true,
          explanation: 'Correct. Electronic control means the transistor can be switched by a circuit signal — enabling automation, speed, and remote operation that mechanical switches cannot provide.',
        },
        {
          id: 'ch2-c',
          label: 'A transistor switch operates at higher voltage than a mechanical switch',
          isCorrect: false,
          explanation: 'Operating voltage is not the defining advantage here. The key difference is how the switch is controlled — electronically vs physically.',
        },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Transistor ON and OFF States',
      content: 'When a transistor\'s control is enabled, it conducts — behaving like a closed switch. When the control is disabled, it blocks — behaving like an open switch. These two states are directly analogous to a mechanical switch, but the transistor achieves them through an electronic signal rather than physical movement.',
    },
    {
      title: 'Electronic vs Mechanical Switching',
      content: 'A mechanical switch requires physical action to open or close. A transistor is switched by an electronic control signal. This makes the transistor suitable for automated, high-speed, and programmatic switching — applications where physical contact-based switching is impractical.',
    },
  ],
  sandboxUnlocks: ['transistor-switch-example'],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: false,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch8-transistor-switch',
      title: 'Transistor as a simplified switch',
      content: 'A transistor with its control enabled conducts like a closed switch. A transistor with its control disabled blocks like an open switch. Unlike a mechanical switch that requires physical contact to change state, the transistor is toggled by an electronic signal — making it suitable for automated and high-speed circuit control.',
      sourceLesson: 'lesson-ch8-3-2',
    },
  ],
  quizzesUnlocked: ['quiz-ch8-transistor-switch-basics'],
};
