import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_8_METADATA, CH8_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh8_4_1: LessonConfig = {
  id: 'lesson-ch8-4-1',
  unitId: 'ch8-unit-4',
  title: 'Diode or Transistor?',
  description: 'Learn to choose between a diode and a transistor by identifying the design goal: use a diode for directional enforcement and a transistor when one part of the circuit needs to control another.',
  stageLabel: CHAPTER_8_METADATA.stageLabel,
  prerequisites: ['lesson-ch8-3-3'],
  conceptsIntroduced: [
    'component choice by purpose',
    'diode and transistor solve different classes of problems',
  ],
  initialNodes: CH8_COMPARISON_NODES,
  initialCircuit: [
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'Battery (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'diode-1',
      type: 'diode',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { isForwardBiased: true },
      name: 'Diode',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    {
      id: 'bat-2',
      type: 'battery',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { voltage: 9 },
      name: 'Battery (9V)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'transistor-1',
      type: 'transistor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { controlEnabled: true },
      name: 'Transistor',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'Both diodes and transistors are active components, but they solve different problems. A diode enforces direction — it automatically allows current in one orientation and blocks it in the other. No external signal is needed; the behavior is determined by how the diode is oriented in the circuit. Choose a diode when your goal is to control the direction of current flow.',
      highlights: ['diode-1'],
    },
    {
      id: 'step-2',
      text: 'A transistor solves a different problem: control. One part of the circuit (the control signal) determines whether another part (the main current path) can operate. The transistor is a gate that opens or closes based on an external signal from elsewhere in the system. Choose a transistor when one part of the circuit needs to govern another.',
      highlights: ['transistor-1'],
    },
    {
      id: 'step-3',
      text: 'The decision rule is straightforward. If the design goal is directionality — ensuring current can only flow one way — choose a diode. If the design goal is control — enabling one circuit path to switch another on or off — choose a transistor. Looking at both circuits side by side, notice how the diode (left) enforces a fixed current direction while the transistor (right) waits for a control condition.',
      highlights: ['diode-1', 'transistor-1'],
      theoryCheck: {
        question: 'A design requires that current only flows in one direction regardless of source polarity. Which component should be used?',
        choices: [
          {
            id: 'tc-a',
            label: 'A transistor — it can be programmed to block reverse current',
            isCorrect: false,
            explanation: 'A transistor requires an external control signal to operate. Blocking reverse current automatically, without any control input, is precisely what a diode does.',
          },
          {
            id: 'tc-b',
            label: 'A diode — it enforces directionality without any external control signal',
            isCorrect: true,
            explanation: 'Correct. A diode\'s directional behavior is intrinsic to its orientation — no external control signal is needed. It automatically allows current in one direction and blocks the other.',
          },
          {
            id: 'tc-c',
            label: 'Either component can enforce directionality equally well',
            isCorrect: false,
            explanation: 'Only the diode enforces directionality automatically by its orientation. A transistor enforces a control condition, not a directional condition.',
          },
        ],
        explanation: 'When the goal is directional enforcement — allowing current in only one orientation — a diode is the correct choice. It achieves this automatically based on its placement, without requiring any external control signal.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'You need a circuit where a small electronic signal can turn a large load on or off remotely. Which component is the right choice?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-b' },
      hints: [
        'Think about which component responds to a separate control signal.',
        'One component is controlled by another part of the circuit; the other responds only to its own orientation.',
      ],
      choices: [
        {
          id: 'ch1-a',
          label: 'A diode — it can be oriented to pass only the signals that match the load direction',
          isCorrect: false,
          explanation: 'A diode responds to its physical orientation and the direction of current, not to a separate electronic control signal. It cannot be turned on or off by a remote signal.',
        },
        {
          id: 'ch1-b',
          label: 'A transistor — it is controlled by a separate signal and can switch a larger load path',
          isCorrect: true,
          explanation: 'Correct. A transistor is designed for exactly this role. A small control signal enables or disables the transistor, which in turn controls whether the larger load path conducts current.',
        },
        {
          id: 'ch1-c',
          label: 'Either component works — the choice depends only on voltage level',
          isCorrect: false,
          explanation: 'The choice depends on the design goal, not the voltage level. When remote electronic control is required, a transistor is the right component.',
        },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'You need to protect a sensitive component from reverse current. Which component is the right choice?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-a' },
      hints: [
        'Reverse current protection means blocking current that flows in the wrong direction.',
        'One component does this automatically based on orientation; the other requires a separate control signal.',
      ],
      choices: [
        {
          id: 'ch2-a',
          label: 'A diode — it automatically blocks reverse current based on orientation',
          isCorrect: true,
          explanation: 'Correct. Placing a diode in the forward orientation relative to the intended current flow automatically prevents reverse current from reaching the protected component. No control signal is needed.',
        },
        {
          id: 'ch2-b',
          label: 'A transistor — it can block current in both directions when the control is disabled',
          isCorrect: false,
          explanation: 'A transistor blocks current based on a control condition, not based on current direction. It is not the right tool for directional protection.',
        },
        {
          id: 'ch2-c',
          label: 'A resistor — high resistance limits reverse current to a safe level',
          isCorrect: false,
          explanation: 'A resistor reduces current but does not block it directionally. Reverse current would still flow through a resistor, just at a reduced level.',
        },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Choosing Between a Diode and a Transistor',
      content: 'Diodes and transistors are both active components but serve fundamentally different purposes. A diode enforces directionality: it conducts in one orientation and blocks in the other, automatically. A transistor enables control: it allows one part of a circuit to govern whether another path conducts. The design question is "what is the goal?" — directionality selects the diode; control selects the transistor.',
    },
    {
      title: 'Why Purpose-Driven Component Selection Matters',
      content: 'Using the wrong component for a design goal leads to a non-functional circuit. A transistor cannot protect against reverse current by orientation alone, and a diode cannot respond to a remote electronic control signal. Identifying the design goal first is the most reliable way to select the correct active component.',
    },
  ],
  sandboxUnlocks: [],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: false,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch8-diode-or-transistor',
      title: 'Choosing Between Diode and Transistor',
      content: 'Use a diode when the design goal is directional enforcement: allowing current in one orientation and blocking it in the other, automatically. Use a transistor when the design goal is control: enabling one part of the circuit to switch another part on or off via a separate signal. The distinction is goal-driven, not voltage- or power-driven.',
      sourceLesson: 'lesson-ch8-4-1',
    },
  ],
  quizzesUnlocked: ['quiz-ch8-component-choice-basics'],
};
