import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_8_METADATA, CH8_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh8_2_1: LessonConfig = {
  id: 'lesson-ch8-2-1',
  unitId: 'ch8-unit-2',
  title: 'Why a Diode Matters for AC',
  description: 'See what happens when a diode meets an AC source, and connect this to the abstract AC-to-DC block from Chapter 7.',
  stageLabel: CHAPTER_8_METADATA.stageLabel,
  prerequisites: ['lesson-ch8-1-3'],
  conceptsIntroduced: [
    'diode directionality visible in AC context',
    'diode blocks one half of the AC cycle',
    'connection: the abstract AC-to-DC conversion block from Chapter 7 is realized by diode-based circuits',
  ],
  initialNodes: CH8_COMPARISON_NODES,
  initialCircuit: [
    // Left side: AC without diode (nodes n1–n4)
    {
      id: 'ac-1',
      type: 'ac-source',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: AC with diode (nodes n5–n8)
    {
      id: 'ac-2',
      type: 'ac-source',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'diode-1',
      type: 'diode',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { isForwardBiased: true },
      name: 'Diode',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-3',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'In Chapter 7, you used an abstract AC-to-DC conversion block. In this unit, we begin to open that black box. The diode is the key ingredient. The question is: what does a diode actually do when AC flows through a circuit?',
      highlights: ['ac-1', 'ac-2'],
    },
    {
      id: 'step-2',
      text: 'Look at both circuits. On the left, the load receives the full AC signal — current alternates in both directions over time. On the right, the diode is in series with the load. The diode blocks the reverse half of every AC cycle, so only the forward half of the cycle reaches the load.',
      highlights: ['res-1', 'diode-1', 'res-2'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-3',
      text: 'By blocking the reverse half of the AC cycle, the diode ensures the load only receives current that flows in one direction. This is the first step toward converting AC into something more DC-like. The diode does not produce smooth DC — but it removes the negative half, which is where the conversion process starts.',
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'When a diode is placed in series with an AC source and load, what happens to the current through the load?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-b' },
      hints: ['Think about what a diode does to current direction based on what you learned in Unit 1.'],
      choices: [
        {
          id: 'ch1-a',
          label: 'The diode amplifies the current so the load receives more than with AC alone',
          isCorrect: false,
          explanation: 'A diode does not amplify current. It only controls direction.',
        },
        {
          id: 'ch1-b',
          label: 'The diode blocks the reverse half of the AC cycle so the load only receives current in one direction',
          isCorrect: true,
          explanation: 'Correct. The diode passes the forward half-cycle and blocks the reverse half-cycle, so the load only sees one-directional current pulses.',
        },
        {
          id: 'ch1-c',
          label: 'The diode converts AC into perfectly smooth DC',
          isCorrect: false,
          explanation: 'A single diode produces pulsed one-directional current, not smooth DC. Smooth DC requires additional filtering stages.',
        },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'How does the diode-in-AC behavior relate to the abstract AC-to-DC conversion block from Chapter 7?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Think about what the AC-to-DC block was described as doing in Chapter 7, and which part of that the diode performs.'],
      choices: [
        {
          id: 'ch2-a',
          label: 'The diode replaces the AC source, making a DC source unnecessary',
          isCorrect: false,
          explanation: 'The diode does not generate power. It shapes the existing AC signal.',
        },
        {
          id: 'ch2-b',
          label: 'The diode is the core component that makes that conversion possible — it removes the negative half of the AC cycle',
          isCorrect: true,
          explanation: 'Correct. The abstract AC-to-DC block from Chapter 7 is realized by diode-based circuits. The diode performs the first essential step: blocking reverse current.',
        },
        {
          id: 'ch2-c',
          label: 'The diode and the AC-to-DC block are unrelated — the block uses a different mechanism',
          isCorrect: false,
          explanation: 'They are directly related. The AC-to-DC conversion block is built around diode-based rectification.',
        },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Diodes Under AC',
      content: 'When an AC source drives a circuit containing a diode, the diode blocks the reverse half of every cycle. The load only receives current during the forward half-cycles. This one-directional pulsing is the foundation of AC-to-DC conversion.',
    },
    {
      title: 'Opening the AC-to-DC Black Box',
      content: 'The abstract AC-to-DC conversion block introduced in Chapter 7 is realized by diode-based circuits. The diode removes the negative half of the AC cycle, which is the first step in producing a DC-like output from an AC source.',
    },
  ],
  sandboxUnlocks: ['ac-diode-experiment'],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: true,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch8-diode-ac',
      title: 'Diodes under AC at an introductory level',
      content: 'When a diode is placed in series with an AC source, it blocks the reverse half of each cycle. The load only sees current flowing in one direction — during the forward half-cycles. This is the starting point for understanding how AC can be converted to DC using diode circuits.',
      sourceLesson: 'lesson-ch8-2-1',
    },
  ],
  quizzesUnlocked: ['quiz-ch8-diode-and-ac-basics'],
};
