import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_7_METADATA, CH7_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh7_2_1: LessonConfig = {
  id: 'lesson-ch7-2-1',
  unitId: 'ch7-unit-2',
  title: 'The Same Load, Different Source Type',
  description: 'Connect the same resistor to both a DC and an AC source and observe how source type changes circuit behavior.',
  stageLabel: CHAPTER_7_METADATA.stageLabel,
  prerequisites: ['lesson-ch7-1-3'],
  conceptsIntroduced: [
    'source type changes circuit behavior',
    'the load must be understood in context of source type',
  ],
  initialNodes: CH7_COMPARISON_NODES,
  initialCircuit: [
    // Left side: DC + resistor
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'DC Source (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'Resistor',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: AC + resistor
    {
      id: 'ac-1',
      type: 'ac-source',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { resistance: 100 },
      name: 'Resistor',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-3',
      type: 'wire',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-4',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'The left circuit connects a 100Ω resistor to a DC source. The current through the resistor is constant — it maintains the same value at every moment in time. You can inspect the resistor and the current overlay will show a steady, unchanging flow.',
      highlights: ['bat-1', 'res-1'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-2',
      text: 'The right circuit connects the same 100Ω resistor to an AC source. Even though the resistor is identical, the current through it now alternates — it rises, falls, reverses direction, and repeats. The source type completely determines the current behavior, not just the load.',
      highlights: ['ac-1', 'res-2'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-3',
      text: 'Open the timeline panel and compare both circuits. The DC side shows a flat constant line. The AC side shows a repeating wave. The resistor has not changed — only the source. This is why understanding source type is essential when analyzing a load.',
      theoryCheck: {
        question: 'Two identical resistors are connected — one to DC and one to AC. Which statement is true?',
        choices: [
          { id: 'tc-a', label: 'Both resistors carry identical current at all times', isCorrect: false, explanation: 'The source type determines the current behavior. The DC resistor carries constant current; the AC resistor carries alternating current.' },
          { id: 'tc-b', label: 'The source type determines the current pattern even when the load is the same', isCorrect: true, explanation: 'Correct. An identical resistor will show constant current under DC and alternating current under AC.' },
          { id: 'tc-c', label: 'The AC resistor carries more current because AC has higher energy', isCorrect: false, explanation: 'The amount of current depends on voltage and resistance, not on whether the source is AC or DC. Here both have 9V amplitude.' },
        ],
        explanation: 'Source type determines the current pattern. An identical load behaves differently under DC (constant current) versus AC (alternating current).',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'The same resistor is connected to a DC source on the left and an AC source on the right. Which side shows constant current throughout?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-a' },
      hints: ['Compare the timeline patterns for both circuits.'],
      choices: [
        { id: 'ch1-a', label: 'The DC side', isCorrect: true, explanation: 'Correct. The DC source drives a constant current through the resistor. The timeline for the DC side is a flat line.' },
        { id: 'ch1-b', label: 'The AC side', isCorrect: false, explanation: 'The AC side shows alternating current. The timeline oscillates above and below zero rather than staying constant.' },
        { id: 'ch1-c', label: 'Both sides show constant current', isCorrect: false, explanation: 'Only the DC side is constant. The AC side alternates.' },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'Which statement best describes how the source type affects the same load?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Think about what changes between the two circuits in this lesson.'],
      choices: [
        { id: 'ch2-a', label: 'The load type determines the current pattern regardless of source', isCorrect: false, explanation: 'In this lesson, the same load (resistor) produces different current behavior depending on source type. The source is what determines the pattern.' },
        { id: 'ch2-b', label: 'The load receives constant current from DC but alternating current from AC', isCorrect: true, explanation: 'Correct. An identical resistive load shows constant current under DC and alternating current under AC.' },
        { id: 'ch2-c', label: 'Source type does not affect the load if the voltage amplitude is the same', isCorrect: false, explanation: 'Even at the same amplitude, DC produces constant current while AC produces alternating current. The type of variation matters, not just the peak value.' },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Source Type and Load Behavior',
      content: 'The same load connected to different source types produces different current behavior. A DC source drives constant current; an AC source drives alternating current. Understanding the source is essential to analyzing how a load operates.',
    },
  ],
  sandboxUnlocks: [],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: true,
  formulasShown: [],
  theoryPageAdditions: [],
  quizzesUnlocked: ['quiz-ch7-ac-dc-load-comparison-basics'],
};
