import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_7_METADATA, CH7_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh7_4_2: LessonConfig = {
  id: 'lesson-ch7-4-2',
  unitId: 'ch7-unit-4',
  title: 'Compare Direct Connection and Converted Connection',
  description: 'See why connecting a DC source directly to an AC load fails, and why inserting a converter makes the system work correctly.',
  stageLabel: CHAPTER_7_METADATA.stageLabel,
  prerequisites: ['lesson-ch7-4-1'],
  conceptsIntroduced: [
    'direct mismatch versus compatible system design',
    'conversion is part of correct system design, not an arbitrary add-on',
  ],
  initialNodes: CH7_COMPARISON_NODES,
  initialCircuit: [
    // Left side: incorrect — DC source directly connected to AC load, no converter (nodes n1–n4)
    {
      id: 'bat-left',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'DC Source',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-left',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'AC Load (direct)',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-left',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    {
      id: 'wire-left-2',
      type: 'wire',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    // Right side: correct — DC source → DC-to-AC converter → AC load (nodes n5–n8)
    {
      id: 'bat-right',
      type: 'battery',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { voltage: 9 },
      name: 'DC Source',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'conv-right',
      type: 'dc-ac-converter',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: {},
      name: 'DC-to-AC Converter',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-right',
      type: 'resistor',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { resistance: 100 },
      name: 'AC Load',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-right',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'Look at the left circuit. A DC source is connected directly to a component labeled "AC Load." There is no conversion stage between them. The source outputs direct current only — it cannot produce the alternating current that an AC load requires. The source and load types are mismatched. The AC load will not operate correctly under DC conditions.',
      highlights: ['bat-left', 'res-left'],
    },
    {
      id: 'step-2',
      text: 'Now look at the right circuit. The same DC source feeds a DC-to-AC converter, which in turn connects to the AC load. The converter bridges the gap between source and load types. The AC load now receives alternating current as it requires. This is the correctly designed system.',
      highlights: ['bat-right', 'conv-right', 'res-right'],
    },
    {
      id: 'step-3',
      text: 'The left circuit has a source-type mismatch: DC where AC is needed. The right circuit resolves the mismatch with a conversion stage. Conversion is not an optional upgrade — it is a required part of the design whenever source and load types are incompatible.',
      theoryCheck: {
        question: 'Why does the left circuit fail to correctly power the AC load?',
        choices: [
          { id: 'tc-a', label: 'The DC source voltage is too low to power the AC load', isCorrect: false, explanation: 'The issue is not voltage level — it is current type. Even at the same voltage, DC cannot provide the alternating current an AC load requires.' },
          { id: 'tc-b', label: 'The DC source provides only one-directional current, but the AC load requires alternating current — the types are incompatible', isCorrect: true, explanation: 'Correct. The fundamental mismatch is current type: DC is unidirectional, but AC loads need alternating current.' },
          { id: 'tc-c', label: 'The left circuit is missing a resistor in series with the DC source', isCorrect: false, explanation: 'Adding a series resistor does not fix a source-type mismatch. The problem is that DC cannot substitute for AC.' },
        ],
        explanation: 'Source-type mismatch occurs when a DC source drives an AC load without a conversion stage. The load needs alternating current, which the DC source cannot provide.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'Which system is correctly designed to power an AC load from a DC source?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-b' },
      hints: ['One system has a converter between the source and load; the other does not.'],
      choices: [
        { id: 'ch1-a', label: 'The left system with the DC source connected directly to the AC load', isCorrect: false, explanation: 'The left system has a source-type mismatch. Direct connection of DC to an AC load does not provide the alternating current the load requires.' },
        { id: 'ch1-b', label: 'The right system with the DC-to-AC converter between source and load', isCorrect: true, explanation: 'Correct. The right system inserts a DC-to-AC converter to bridge the source and load types, making them compatible.' },
        { id: 'ch1-c', label: 'Both systems are equivalent since they use the same voltage and resistance values', isCorrect: false, explanation: 'Matching voltage and resistance values does not resolve a source-type mismatch. The current type provided must match what the load requires.' },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'What is the main conceptual error in directly connecting a DC source to an AC load?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-c' },
      hints: ['Focus on what the load expects versus what the source provides.'],
      choices: [
        { id: 'ch2-a', label: 'The circuit will overheat because DC delivers too much power to an AC-rated component', isCorrect: false, explanation: 'While power rating concerns are real, the fundamental conceptual error is the source-type mismatch, not a power level issue.' },
        { id: 'ch2-b', label: 'A DC source cannot be used in any circuit that also contains an AC load', isCorrect: false, explanation: 'A DC source can power an AC load — but only through a conversion stage. It is not impossible, just requires the correct architecture.' },
        { id: 'ch2-c', label: 'The source type and load requirement do not match — the load expects alternating current but the DC source provides only constant current', isCorrect: true, explanation: 'Correct. This is the core mismatch: the AC load needs alternating current, but the DC source delivers only unidirectional, constant current.' },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Source-Type Mismatch',
      content: 'When a DC source is connected directly to an AC load, the current type does not match the load requirement. The load expects alternating current; the source provides only direct current. The system fails to operate correctly.',
    },
    {
      title: 'Conversion as Required Design Element',
      content: 'Inserting a DC-to-AC converter between a DC source and an AC load resolves the type mismatch. The converter is not an optional extra — it is a necessary part of any system where source and load types differ.',
    },
  ],
  sandboxUnlocks: [],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: false,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch7-source-load-matching-conversion',
      title: 'Matching Source Type to Load Type Through Conversion',
      content: 'When source and load types differ (e.g., DC source, AC load), a conversion stage is required. Without it, the system has a fundamental type mismatch that no voltage or resistance adjustment can fix. Conversion must be part of the system design.',
      sourceLesson: 'lesson-ch7-4-2',
    },
  ],
  quizzesUnlocked: ['quiz-ch7-source-type-matching-with-conversion'],
};
