import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_7_METADATA, CH7_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh7_1_2: LessonConfig = {
  id: 'lesson-ch7-1-2',
  unitId: 'ch7-unit-1',
  title: 'AC Changes Over Time in a Different Way',
  description: 'Use the timeline panel to distinguish between one-time transient behavior and the repeating pattern of AC.',
  stageLabel: CHAPTER_7_METADATA.stageLabel,
  prerequisites: ['lesson-ch7-1-1'],
  conceptsIntroduced: [
    'repeating AC pattern',
    'difference between transient behavior and AC behavior',
    'transient settles to flat line; AC keeps repeating',
  ],
  initialNodes: CH7_COMPARISON_NODES,
  initialCircuit: [
    // Left side: DC + resistor + switch (transient reference)
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'DC Source (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'Resistor',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'sw-1',
      type: 'switch',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { isClosed: false },
      name: 'Switch',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: AC circuit (nodes n5–n8)
    {
      id: 'ac-1',
      type: 'ac-source',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { resistance: 100 },
      name: 'Resistor (AC)',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-3',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'In Chapter 6 you saw transient behavior: a circuit that changes for a while after a switch is closed, then settles to a constant steady state. A transient is a one-time change. Once the circuit has settled, the timeline panel shows a flat line. Close the switch on the left side to see this.',
      requiredAction: { type: 'toggle-switch', componentId: 'sw-1', targetState: true },
      highlights: ['sw-1', 'res-1'],
    },
    {
      id: 'step-2',
      text: 'Now look at the AC circuit on the right. It has no switch — it is always running. Open the timeline panel. Unlike the transient that flattens out, the AC timeline keeps repeating the same pattern indefinitely. The voltage and current cycle through positive and negative values without ever settling to a constant level.',
      highlights: ['ac-1', 'res-2'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-3',
      text: 'The key distinction: a transient is a one-time event that ends in steady state. AC is a continuous, repeating pattern that never settles. Both involve changing values over time, but they change in fundamentally different ways.',
      theoryCheck: {
        question: 'How does transient behavior differ from AC behavior over time?',
        choices: [
          { id: 'tc-a', label: 'Both transient and AC patterns repeat indefinitely', isCorrect: false, explanation: 'Only AC repeats indefinitely. A transient is a one-time change that ends when the circuit reaches steady state.' },
          { id: 'tc-b', label: 'Transient behavior settles to a constant value; AC keeps repeating without settling', isCorrect: true, explanation: 'Correct. A transient ends in steady state. AC is a continuous repeating pattern.' },
          { id: 'tc-c', label: 'AC behavior always occurs after a switch is toggled, just like a transient', isCorrect: false, explanation: 'Transients are triggered by switching events. AC behavior is continuous and independent of switch events.' },
        ],
        explanation: 'A transient is a one-time change that ends at steady state. AC is an ongoing repeating pattern.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'Which timeline pattern shows behavior that eventually flattens to a constant value?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-a' },
      hints: ['Think about which circuit has a switch that closes once, and what happens to a transient after time passes.'],
      choices: [
        { id: 'ch1-a', label: 'The RC transient pattern (from closing a switch)', isCorrect: true, explanation: 'Correct. A transient is a one-time change. After the circuit settles, the timeline shows a constant flat line.' },
        { id: 'ch1-b', label: 'The AC source pattern', isCorrect: false, explanation: 'The AC timeline never flattens. It continues repeating its oscillating pattern without settling.' },
        { id: 'ch1-c', label: 'Both patterns flatten equally over time', isCorrect: false, explanation: 'Only the transient flattens to steady state. AC maintains its repeating pattern indefinitely.' },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'Which source produces a repeating pattern that never settles to a constant value?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Compare how the timeline looks for each circuit in the lesson.'],
      choices: [
        { id: 'ch2-a', label: 'A DC source connected through a switch', isCorrect: false, explanation: 'A DC source with a switch produces a transient that eventually settles to a constant steady state.' },
        { id: 'ch2-b', label: 'An AC source', isCorrect: true, explanation: 'Correct. An AC source produces an ongoing repeating pattern. It never settles to a constant level.' },
        { id: 'ch2-c', label: 'A DC source without a switch', isCorrect: false, explanation: 'A DC source without a switch instantly drives a constant current. Its timeline is always flat.' },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Repeating AC Behavior',
      content: 'AC circuits produce a continuous, repeating pattern of voltage and current. Unlike a transient that settles to a constant steady state, AC behavior continues indefinitely without settling.',
    },
    {
      title: 'AC versus Transient Change',
      content: 'Transient behavior is a one-time event triggered by a circuit change (such as closing a switch). It ends in steady state. AC behavior is fundamentally different: it is an ongoing repeating cycle that never settles.',
    },
  ],
  sandboxUnlocks: [],
  availableActions: ['toggle-switch', 'inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: true,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch7-repeating-ac',
      title: 'Repeating AC Behavior',
      content: 'AC sources produce a continuous repeating cycle of voltage and current. Unlike DC transients — which are one-time changes that end in steady state — AC behavior keeps repeating indefinitely.',
      sourceLesson: 'lesson-ch7-1-2',
    },
    {
      id: 'theory-ch7-ac-vs-transient',
      title: 'AC versus Transient Change',
      content: 'A transient is triggered by a switching event and eventually settles to a steady state flat line. AC is an ongoing repeating pattern. Both involve changing values over time, but in fundamentally different ways.',
      sourceLesson: 'lesson-ch7-1-2',
    },
  ],
  quizzesUnlocked: ['quiz-ch7-ac-time-pattern-basics'],
};
