import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_8_METADATA, CH8_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh8_1_2: LessonConfig = {
  id: 'lesson-ch8-1-2',
  unitId: 'ch8-unit-1',
  title: 'Orientation Matters',
  description: 'Compare a forward-biased diode to a reversed diode side by side and see how orientation alone determines whether the load operates.',
  stageLabel: CHAPTER_8_METADATA.stageLabel,
  prerequisites: ['lesson-ch8-1-1'],
  conceptsIntroduced: [
    'orientation dependence',
    'one-way behavior in the instructional model',
    'placement alone is not enough — orientation matters',
  ],
  initialNodes: CH8_COMPARISON_NODES,
  initialCircuit: [
    // Left side: forward-biased diode (nodes n1–n4)
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'Battery (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'diode-1',
      type: 'diode',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { isForwardBiased: true },
      name: 'Diode (Forward)',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: reversed diode (nodes n5–n8)
    {
      id: 'bat-2',
      type: 'battery',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { voltage: 9 },
      name: 'Battery (9V)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'diode-2',
      type: 'diode',
      nodeA: 'n6',
      nodeB: 'n5',
      properties: { isForwardBiased: false },
      name: 'Diode (Reversed)',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'Look at the left circuit. The diode is oriented in the same direction that current wants to flow — this is the forward-biased orientation. Current flows from the battery, through the forward-biased diode, and through the load. The load is operating.',
      highlights: ['bat-1', 'diode-1', 'res-1'],
      showCurrentOverlay: true,
    },
    {
      id: 'step-2',
      text: 'Now look at the right circuit. The diode has been flipped — it is oriented against the direction of current flow. This is the reverse-biased orientation. The diode blocks the current path. No current reaches the load, and the load does not operate.',
      highlights: ['bat-2', 'diode-2', 'res-2'],
    },
    {
      id: 'step-3',
      text: 'Both circuits use identical components and the same battery voltage. The only difference is the orientation of the diode. In one circuit the load operates; in the other it does not. Orientation alone determines the outcome.',
      highlights: ['diode-1', 'diode-2'],
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'Which circuit has the diode oriented so that current can flow through the load?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-a' },
      hints: ['A forward-biased diode is oriented in the same direction as current flow.'],
      choices: [
        {
          id: 'ch1-a',
          label: 'The left circuit with the forward-biased diode',
          isCorrect: true,
          explanation: 'Correct. The left circuit has the diode in the forward-biased orientation, allowing current to reach the load.',
        },
        {
          id: 'ch1-b',
          label: 'The right circuit with the reversed diode',
          isCorrect: false,
          explanation: 'The right circuit has the diode reversed. It blocks the current path, so the load receives no current.',
        },
        {
          id: 'ch1-c',
          label: 'Both circuits allow current through the load',
          isCorrect: false,
          explanation: 'Only the forward-biased diode allows current. The reversed diode blocks the path entirely.',
        },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'The diode in the right circuit is reversed. What happens to the load?',
      type: 'fix',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Think about what a reversed diode does to the current path in the simplified model.'],
      choices: [
        {
          id: 'ch2-a',
          label: 'The load still operates normally (incorrect — a reversed diode blocks current)',
          isCorrect: false,
          explanation: 'A reversed diode blocks current completely in the simplified model. The load cannot operate.',
        },
        {
          id: 'ch2-b',
          label: 'The load receives no current because the reversed diode blocks the path',
          isCorrect: true,
          explanation: 'Correct. In the simplified model, a reversed diode acts as an open circuit. No current reaches the load.',
        },
        {
          id: 'ch2-c',
          label: 'The diode catches fire — not how this simplified model works',
          isCorrect: false,
          explanation: 'In the simplified instructional model, a reversed diode simply blocks current. No component damage is modeled here.',
        },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Forward-Biased vs Reverse-Biased',
      content: 'A diode oriented in the same direction as current flow is forward-biased and conducts. A diode oriented against the direction of current flow is reverse-biased and blocks. In the simplified model, a reversed diode acts as a complete open circuit.',
    },
    {
      title: 'Why Orientation Matters',
      content: 'Placing a diode in a circuit is not enough — its orientation determines the outcome. Two otherwise identical circuits with the same components can produce completely different results depending on which way the diode is placed.',
    },
  ],
  sandboxUnlocks: [],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: false,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch8-orientation',
      title: 'Why diode orientation matters',
      content: 'A forward-biased diode allows current to pass. A reverse-biased diode blocks current. Identical circuits with the same components produce different outcomes depending solely on diode orientation. Placing a diode correctly is essential to achieving the intended circuit behavior.',
      sourceLesson: 'lesson-ch8-1-2',
    },
  ],
  quizzesUnlocked: ['quiz-ch8-diode-orientation-basics'],
};
