import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_7_METADATA, CH7_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh7_5_1: LessonConfig = {
  id: 'lesson-ch7-5-1',
  unitId: 'ch7-unit-5',
  title: 'AC Versus DC Review Challenge',
  description: 'Consolidate your Chapter 7 understanding: classify source types, identify correct conversion strategies, and review the key distinctions between DC and AC systems.',
  stageLabel: CHAPTER_7_METADATA.stageLabel,
  prerequisites: ['lesson-ch7-4-2'],
  conceptsIntroduced: [],
  initialNodes: CH7_COMPARISON_NODES,
  initialCircuit: [
    // Left side: DC circuit (nodes n1–n4)
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'DC Source (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: AC circuit (nodes n5–n8)
    {
      id: 'ac-1',
      type: 'ac-source',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-3',
      type: 'wire',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-4',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'This is a review of Chapter 7. On the left is a DC circuit: a battery drives a resistive load with constant, one-directional current. On the right is an AC circuit: an AC source drives a resistive load with continuously alternating current. DC is steady and one-directional; AC alternates direction on a repeating cycle. When source and load types differ, a conversion stage — DC-to-AC or AC-to-DC — bridges the mismatch.',
      showCurrentOverlay: true,
    },
    {
      id: 'step-2',
      text: 'Use the timeline panel to compare the two circuits. The DC side shows a flat, constant current line. The AC side shows a repeating wave pattern as the current alternates direction. A system that needs to serve both AC and DC loads from a single source will require selective conversion — only the mismatched loads need a converter.',
      theoryCheck: {
        question: 'A battery-based DC system must power one DC-only device and one AC-only device. Which conversion strategy is correct?',
        choices: [
          { id: 'tc-a', label: 'Add a DC-to-AC converter on every branch, including the DC device branch, to be safe', isCorrect: false, explanation: 'Converting DC to AC on the DC device branch would break the DC device. Conversion is only needed where there is a type mismatch.' },
          { id: 'tc-b', label: 'Connect both devices directly to the DC source without any conversion', isCorrect: false, explanation: 'The AC device requires AC, which a DC source cannot provide. Direct connection would be a source-type mismatch for the AC device.' },
          { id: 'tc-c', label: 'Connect the DC device directly to the source and insert a DC-to-AC converter only on the AC device branch', isCorrect: true, explanation: 'Correct. The DC device is already compatible with the DC source. Only the AC device branch needs a converter to resolve the type mismatch.' },
        ],
        explanation: 'Conversion is needed only where there is a source-load type mismatch. In a DC system with mixed loads, insert converters only on branches with AC loads.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'Which source provides a continuously alternating current through a connected load?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-b' },
      hints: ['Look at the right side of the workspace — observe the source type and its effect on current direction.'],
      choices: [
        { id: 'ch1-a', label: 'The DC source (battery)', isCorrect: false, explanation: 'A battery provides constant, one-directional current. It never alternates.' },
        { id: 'ch1-b', label: 'The AC source', isCorrect: true, explanation: 'Correct. The AC source on the right drives an alternating current through the load — the current direction reverses on every half-cycle.' },
        { id: 'ch1-c', label: 'Both sources produce alternating current but at different rates', isCorrect: false, explanation: 'Only the AC source alternates. The DC source (battery) never produces alternating current.' },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'A DC source needs to drive both a DC load and an AC load. How many conversion stages are needed?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-b' },
      hints: ['Think about each load: is there a type mismatch between the DC source and each load?'],
      choices: [
        { id: 'ch2-a', label: 'Two — one conversion stage for each load regardless of type', isCorrect: false, explanation: 'Converting the DC load branch is unnecessary and would break the DC device. Conversion is only needed where there is a type mismatch.' },
        { id: 'ch2-b', label: 'One — only the AC load needs a DC-to-AC conversion stage; the DC load can connect directly', isCorrect: true, explanation: 'Correct. The DC load is already compatible with the DC source. Only the AC load has a type mismatch, requiring a single DC-to-AC conversion stage.' },
        { id: 'ch2-c', label: 'Zero — DC sources can power both DC and AC loads without conversion', isCorrect: false, explanation: 'A DC source cannot directly supply AC current. The AC load requires a conversion stage to receive alternating current.' },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Chapter 7 Review: DC vs AC',
      content: 'DC (Direct Current) flows in one constant direction. AC (Alternating Current) repeatedly reverses direction. The source type determines the nature of the current in the circuit. When source and load types differ, a conversion stage is required.',
    },
    {
      title: 'Selective Conversion in Multi-Load Systems',
      content: 'When a single source must drive multiple loads of different types, only the mismatched branches require conversion stages. Adding unnecessary converters on already-compatible branches would break those loads.',
    },
  ],
  sandboxUnlocks: ['ac-dc-comparison-prompt'],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: true,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch7-review',
      title: 'Chapter 7 Review: AC and Conversion',
      content: 'Chapter 7 covers AC fundamentals and DC/AC conversion. Key concepts: DC is constant and unidirectional; AC alternates direction on a repeating cycle. When source and load types differ, a DC-to-AC or AC-to-DC converter is required. Conversion stages should only be placed where there is an actual type mismatch.',
      sourceLesson: 'lesson-ch7-5-1',
    },
  ],
  quizzesUnlocked: ['quiz-ch7-chapter-7-review-quiz'],
};
