import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_7_METADATA, CH7_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh7_3_1: LessonConfig = {
  id: 'lesson-ch7-3-1',
  unitId: 'ch7-unit-3',
  title: 'Why Convert Between DC and AC?',
  description: 'Understand why conversion stages exist in real systems by seeing what happens when source and load types do not match.',
  stageLabel: CHAPTER_7_METADATA.stageLabel,
  prerequisites: ['lesson-ch7-2-3'],
  conceptsIntroduced: [
    'source and load types may not match directly',
    'conversion stages solve compatibility problems',
    'modern systems include both DC and AC segments',
    'extension of source-load matching from Chapters 2 and 4',
  ],
  initialNodes: CH7_COMPARISON_NODES,
  initialCircuit: [
    // Left side: DC source + DC load (naturally compatible)
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'DC Source (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { resistance: 100 },
      name: 'DC Load',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    // Right side: AC source + DC load (incompatible without conversion)
    {
      id: 'ac-1',
      type: 'ac-source',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { amplitude: 9, frequency: 60 },
      name: 'AC Source (9V, 60Hz)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { resistance: 100 },
      name: 'DC Load from AC — needs conversion',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'wire-3',
      type: 'wire',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-4',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'In Chapters 2 and 4 you studied source-load matching: the source must be appropriate for the load. A DC load connected directly to a DC source is naturally compatible — the load receives constant, one-directional current. The left circuit shows this ideal situation.',
      highlights: ['bat-1', 'res-1'],
    },
    {
      id: 'step-2',
      text: 'The right side shows a DC-only load connected directly to an AC source. The load is labeled "DC Load from AC — needs conversion." A device designed for DC operation receives alternating current, which reverses direction continuously. This mismatch can produce incorrect operation, overheating, or damage in real devices. A conversion stage is needed between the AC source and the DC load.',
      highlights: ['ac-1', 'res-2'],
    },
    {
      id: 'step-3',
      text: 'Modern systems — like the power supply in your computer or the adapter for your phone — include conversion blocks that translate between DC and AC. The conversion stage acts as an adapter between mismatched source and load types. Without it, the system cannot work correctly.',
      theoryCheck: {
        question: 'Why is a conversion stage needed between an AC source and a DC load?',
        choices: [
          { id: 'tc-a', label: 'Because AC has too much voltage for a DC load', isCorrect: false, explanation: 'Voltage level is a separate concern from source type. The fundamental issue is that AC current alternates direction, which a DC-only load cannot use directly.' },
          { id: 'tc-b', label: 'Because the source type (AC) does not match what the DC load requires', isCorrect: true, explanation: 'Correct. A DC load requires steady, one-directional current. An AC source provides alternating current. A conversion stage bridges this mismatch.' },
          { id: 'tc-c', label: 'Because AC and DC use different wire types', isCorrect: false, explanation: 'AC and DC both use standard conductors. The incompatibility is about current direction, not physical wiring.' },
        ],
        explanation: 'A DC load needs steady unidirectional current. An AC source provides alternating current. A conversion stage resolves this type mismatch.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'A DC-only device needs to be powered. Which source can directly drive it without any conversion?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-a' },
      hints: ['Think about which source type produces steady, one-directional current.'],
      choices: [
        { id: 'ch1-a', label: 'A DC source', isCorrect: true, explanation: 'Correct. A DC source provides constant, one-directional current, which is exactly what a DC-only device needs. No conversion is required.' },
        { id: 'ch1-b', label: 'An AC source', isCorrect: false, explanation: 'An AC source produces alternating current. A DC-only device cannot operate correctly from AC without a conversion stage.' },
        { id: 'ch1-c', label: 'Either — source type does not matter as long as the voltage is correct', isCorrect: false, explanation: 'Source type absolutely matters. A DC-only device requires unidirectional current, which only a DC source provides directly.' },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'When would a conversion stage be needed between a source and load?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch2-c' },
      hints: ['Think about what makes a source compatible or incompatible with a load.'],
      choices: [
        { id: 'ch2-a', label: 'Whenever the load resistance is above 100Ω', isCorrect: false, explanation: 'Resistance value is independent of the need for conversion. The need arises from a type mismatch, not a resistance value.' },
        { id: 'ch2-b', label: 'Only when using very high voltages', isCorrect: false, explanation: 'The need for conversion is about source type (DC vs AC), not voltage level. Type mismatches occur at any voltage.' },
        { id: 'ch2-c', label: 'When the source type (DC or AC) does not match what the load requires', isCorrect: true, explanation: 'Correct. If an AC source must power a DC-only load (or vice versa), a conversion stage is needed to bridge the type incompatibility.' },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Why Convert Between DC and AC?',
      content: 'When the type of a source (DC or AC) does not match what a load requires, a conversion stage is needed. A DC load connected directly to an AC source receives alternating current it cannot use properly. Conversion stages act as adapters between mismatched source and load types.',
    },
    {
      title: 'DC and AC in Modern Systems',
      content: 'Practical systems often include both DC and AC segments. A household power adapter takes AC from the wall and converts it to DC for electronic devices. Understanding when conversion is needed is an extension of the source-load matching concepts introduced in earlier chapters.',
    },
  ],
  sandboxUnlocks: ['dc-ac-converter', 'ac-dc-converter'],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: false,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch7-why-convert',
      title: 'Why Convert Between DC and AC?',
      content: 'Source and load types must be compatible. If an AC source must power a DC-only load, or a DC source must drive an AC load, a conversion stage is required. Modern power systems frequently include both DC and AC segments connected through conversion blocks.',
      sourceLesson: 'lesson-ch7-3-1',
    },
  ],
  quizzesUnlocked: ['quiz-ch7-conversion-need-basics'],
};
