import type { LessonConfig } from '../../../../types/lesson.ts';
import { CHAPTER_8_METADATA, CH8_COMPARISON_NODES } from '../../shared.ts';

export const lessonCh8_5_1: LessonConfig = {
  id: 'lesson-ch8-5-1',
  unitId: 'ch8-unit-5',
  title: 'Review Challenge',
  description: 'Consolidate your understanding of diodes and transistors: review their roles, apply the decision rule, and diagnose a component-choice error.',
  stageLabel: CHAPTER_8_METADATA.stageLabel,
  prerequisites: ['lesson-ch8-4-2'],
  conceptsIntroduced: [],
  initialNodes: CH8_COMPARISON_NODES,
  initialCircuit: [
    {
      id: 'bat-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n3',
      properties: { voltage: 9 },
      name: 'Battery (9V)',
      position: { x: 100, y: 250 },
      rotation: 0,
    },
    {
      id: 'diode-1',
      type: 'diode',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: { isForwardBiased: true },
      name: 'Diode',
      position: { x: 225, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-1',
      type: 'resistor',
      nodeA: 'n2',
      nodeB: 'n4',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 350, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n3',
      nodeB: 'n4',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 225, y: 350 },
      rotation: 0,
    },
    {
      id: 'bat-2',
      type: 'battery',
      nodeA: 'n5',
      nodeB: 'n7',
      properties: { voltage: 9 },
      name: 'Battery (9V)',
      position: { x: 450, y: 250 },
      rotation: 0,
    },
    {
      id: 'transistor-1',
      type: 'transistor',
      nodeA: 'n5',
      nodeB: 'n6',
      properties: { controlEnabled: true },
      name: 'Transistor',
      position: { x: 575, y: 150 },
      rotation: 0,
    },
    {
      id: 'res-2',
      type: 'resistor',
      nodeA: 'n6',
      nodeB: 'n8',
      properties: { resistance: 100 },
      name: 'Load',
      position: { x: 700, y: 250 },
      rotation: 0,
    },
    {
      id: 'wire-2',
      type: 'wire',
      nodeA: 'n7',
      nodeB: 'n8',
      properties: { wireResistance: 0 },
      name: 'Wire',
      position: { x: 575, y: 350 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'This unit consolidates everything covered in Chapter 8. Two circuits are shown side by side. On the left, a diode enforces directionality — current can only flow in the forward-biased orientation. On the right, a transistor enables control — the load operates only when the control condition is met. Both are active components, but they serve fundamentally different design goals.',
      highlights: ['diode-1', 'transistor-1'],
    },
    {
      id: 'step-2',
      text: 'Integration challenge: given a scenario, you must choose the correct component and recognize when the wrong component has been used. Think about what question each component answers: the diode answers "which direction?" and the transistor answers "is the condition met?" These two questions correspond to two distinct classes of design problems.',
      theoryCheck: {
        question: 'Which component is best for rectification — converting the reverse half of AC cycles by blocking it?',
        choices: [
          {
            id: 'tc-a',
            label: 'A transistor — it can block current when its control is disabled',
            isCorrect: false,
            explanation: 'A transistor blocks based on a control condition, not based on current direction. It cannot distinguish forward from reverse current without additional logic.',
          },
          {
            id: 'tc-b',
            label: 'A diode — its directional behavior is what blocks one half of the AC cycle',
            isCorrect: true,
            explanation: 'Correct. Rectification relies on the diode\'s intrinsic directional behavior. The diode passes the forward half of the AC cycle and blocks the reverse half — no control signal required.',
          },
          {
            id: 'tc-c',
            label: 'Either component — both can block current under the right conditions',
            isCorrect: false,
            explanation: 'While both can block current, only the diode does so based on current direction automatically. Rectification requires direction-based blocking, which is the diode\'s defining characteristic.',
          },
        ],
        explanation: 'Rectification is a directional problem: the reverse half of the AC cycle must be blocked based on current direction alone. A diode accomplishes this automatically through its orientation. A transistor would need an external control signal and cannot achieve direction-based blocking on its own.',
      },
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'A circuit needs to prevent reverse current from reaching a sensitive component. Diode or transistor?',
      type: 'choose',
      evaluationCriteria: { correctChoiceId: 'ch1-a' },
      hints: [
        'Reverse current protection is a directional problem.',
        'Which component operates based on current direction rather than an external control condition?',
      ],
      choices: [
        {
          id: 'ch1-a',
          label: 'Diode — passive directionality is exactly what the diode provides',
          isCorrect: true,
          explanation: 'Correct. Protecting against reverse current is a directional goal. A diode placed in the correct orientation will automatically block any current attempting to flow in the reverse direction.',
        },
        {
          id: 'ch1-b',
          label: 'Transistor — it can be disabled to block all current including reverse',
          isCorrect: false,
          explanation: 'A transistor blocked by a disabled control signal blocks all current, not just reverse current. It cannot distinguish direction. If the control were re-enabled, reverse current would flow through.',
        },
        {
          id: 'ch1-c',
          label: 'Either — both can prevent reverse current in the same way',
          isCorrect: false,
          explanation: 'Only the diode provides inherent directional blocking. A transistor\'s blocking behavior is tied to a control signal, not to the direction of current.',
        },
      ],
    },
    {
      id: 'challenge-2',
      prompt: 'A circuit uses a diode where a transistor was needed (control goal), and the control path does nothing. What is the root cause?',
      type: 'diagnose',
      evaluationCriteria: { correctChoiceId: 'ch2-a' },
      hints: [
        'Consider what a diode can and cannot respond to.',
        'The design goal was control — being switchable by a separate signal. Does a diode support that?',
      ],
      choices: [
        {
          id: 'ch2-a',
          label: 'Wrong component type — a diode cannot respond to a control signal; a transistor is needed',
          isCorrect: true,
          explanation: 'Correct. A diode has no control input. It operates purely on orientation and current direction. A design that requires a component to respond to a separate control signal requires a transistor, not a diode.',
        },
        {
          id: 'ch2-b',
          label: 'The diode is reverse-biased and needs to be flipped',
          isCorrect: false,
          explanation: 'Flipping the diode changes its directional orientation, but does not give it the ability to respond to a control signal. The fundamental issue is component type, not orientation.',
        },
        {
          id: 'ch2-c',
          label: 'The battery voltage is too low for diode operation',
          isCorrect: false,
          explanation: 'Voltage level is not the issue here. A diode at any voltage cannot respond to a control signal — that capability simply does not exist in a diode.',
        },
      ],
    },
  ],
  theoryContent: [
    {
      title: 'Chapter 8 in Review: Active Components',
      content: 'Chapter 8 introduced two active components: the diode and the transistor. The diode enforces directionality, enabling rectification and reverse-current protection. The transistor enables control, allowing one circuit path to govern another. Both are more than passive impedance — they actively shape circuit behavior.',
    },
    {
      title: 'Recognizing Wrong-Component Errors',
      content: 'A common design error is using an active component for a goal it was not built for. A diode cannot serve as a controllable switch; a transistor cannot protect against reverse current by direction alone. Diagnosing these errors starts with identifying the design goal and checking whether the chosen component can achieve it.',
    },
  ],
  sandboxUnlocks: ['chapter-8-review-prompt'],
  availableActions: ['inspect'],
  currentOverlayAvailable: true,
  showFormulaPanel: true,
  usesTimeControls: false,
  formulasShown: [],
  theoryPageAdditions: [
    {
      id: 'theory-ch8-review',
      title: 'Chapter 8 Review: Active Components',
      content: 'Diodes and transistors are both active components that go beyond simple resistance. Diodes enforce directionality — they allow current in only one orientation. Transistors enable control — they open or close a path based on an external condition. Choosing between them starts with identifying the design goal: direction or control.',
      sourceLesson: 'lesson-ch8-5-1',
    },
  ],
  quizzesUnlocked: ['quiz-ch8-chapter-8-review-quiz'],
};
