import type { LessonConfig } from '../../types/lesson.ts';

export const lesson1: LessonConfig = {
  id: 'lesson-1',
  title: 'Close the Circuit',
  description: 'Toggle a switch to complete a circuit and light a bulb.',
  initialNodes: [
    { id: 'n1', position: { x: 200, y: 100 } },
    { id: 'n2', position: { x: 400, y: 100 } },
    { id: 'n3', position: { x: 400, y: 300 } },
    { id: 'n4', position: { x: 200, y: 300 } },
  ],
  initialCircuit: [
    {
      id: 'battery-1',
      type: 'battery',
      nodeA: 'n1',
      nodeB: 'n4',
      properties: { voltage: 9 },
      name: 'Battery 1',
      position: { x: 100, y: 200 },
      rotation: 0,
    },
    {
      id: 'wire-1',
      type: 'wire',
      nodeA: 'n1',
      nodeB: 'n2',
      properties: {},
      name: 'Wire 1',
      position: { x: 300, y: 100 },
      rotation: 0,
    },
    {
      id: 'bulb-1',
      type: 'bulb',
      nodeA: 'n2',
      nodeB: 'n3',
      properties: { resistance: 45 },
      name: 'Bulb 1',
      position: { x: 500, y: 200 },
      rotation: 0,
    },
    {
      id: 'switch-1',
      type: 'switch',
      nodeA: 'n4',
      nodeB: 'n3',
      properties: { isClosed: false },
      name: 'Switch 1',
      position: { x: 300, y: 400 },
      rotation: 0,
    },
  ],
  steps: [
    {
      id: 'step-1',
      text: 'Welcome! This is a simple electrical circuit. It has a **battery** (the energy source), a **bulb** (the load), and a **switch**.',
    },
    {
      id: 'step-2',
      text: 'A circuit is a loop. For electricity to flow, the loop must be **closed** — every part must be connected. Right now, the switch is **open**, so no current flows.',
    },
    {
      id: 'step-3',
      text: 'Click the switch to **close the circuit** and light the bulb.',
      requiredAction: { type: 'toggle-switch', componentId: 'switch-1', targetState: true },
      highlights: ['switch-1'],
    },
    {
      id: 'step-4',
      text: 'The bulb lights up! Current is now flowing through the complete loop — from the battery, through the wire, through the bulb, through the switch, and back to the battery.',
      showCurrentOverlay: true,
    },
    {
      id: 'step-5',
      text: 'Try toggling the switch off and on again. Notice how the bulb responds immediately.',
    },
  ],
  challenges: [
    {
      id: 'challenge-1',
      prompt: 'The wire connecting the battery to the bulb is missing. Connect it to light the bulb.',
      type: 'fix',
      initialCircuit: [
        {
          id: 'battery-1',
          type: 'battery',
          nodeA: 'n1',
          nodeB: 'n4',
          properties: { voltage: 9 },
          name: 'Battery 1',
          position: { x: 100, y: 200 },
          rotation: 0,
        },
        {
          id: 'bulb-1',
          type: 'bulb',
          nodeA: 'n2',
          nodeB: 'n3',
          properties: { resistance: 45 },
          name: 'Bulb 1',
          position: { x: 500, y: 200 },
          rotation: 0,
        },
        {
          id: 'switch-1',
          type: 'switch',
          nodeA: 'n4',
          nodeB: 'n3',
          properties: { isClosed: true },
          name: 'Switch 1',
          position: { x: 300, y: 400 },
          rotation: 0,
        },
      ],
      initialNodes: [
        { id: 'n1', position: { x: 200, y: 100 } },
        { id: 'n2', position: { x: 400, y: 100 } },
        { id: 'n3', position: { x: 400, y: 300 } },
        { id: 'n4', position: { x: 200, y: 300 } },
      ],
      evaluationCriteria: {
        circuitMustBeClosed: true,
        targetComponent: 'bulb-1',
        targetProperty: 'power',
        expectedRange: { min: 0.1, max: 1000 },
      },
      hints: [
        'Look at the gap in the circuit. Where is the connection missing?',
        'The battery\'s positive terminal (top) needs to connect to the bulb. Try connecting node n1 to node n2.',
      ],
    },
  ],
  theoryContent: [
    {
      title: 'What is a circuit?',
      content: 'A circuit is a closed loop that allows electricity to flow. It needs at least a source (like a battery) and a load (like a bulb).',
    },
    {
      title: 'Open vs Closed',
      content: 'A closed circuit has a complete path for current. An open circuit has a break — no current flows.',
    },
  ],
  sandboxUnlocks: ['battery', 'switch', 'bulb', 'wire'],
};
